
### GEOMETRY

/Geometry/FullRingInfinity/depth 3. cm
/Geometry/FullRingInfinity/sipm_pitch 7. mm
/Geometry/FullRingInfinity/inner_radius 380. mm
/Geometry/FullRingInfinity/sipm_rows 278
/Geometry/FullRingInfinity/instrumented_faces 1
/Geometry/FullRingInfinity/specific_vertex 0. 0. 0. cm


/Geometry/SiPMpet/efficiency 0.2
/Geometry/SiPMpet/visibility true
/Geometry/SiPMpet/size 6. mm


### GENERATOR
/Generator/Back2back/region AD_HOC

/Actions/PetAnalysisRunAction/histo_file OptTrackInfo
/Actions/PetAnalysisRunAction/ntuple_file OpticalEvtInfo

### VERBOSITIES
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132312

### OUTPUT FILE

/petalosim/persistency/start_id 0
/petalosim/persistency/sns_only false
/petalosim/persistency/tof_time 50. nanosecond
/petalosim/persistency/output_file full_body.pet
