### GEOMETRY
/Geometry/PetBox/visibility true
/Geometry/PetBox/tile_type_d HamamatsuVUV
/Geometry/PetBox/tile_type_c FBK
/Geometry/PetBox/single_tile_coinc_plane 1

/Geometry/PetBox/tile_vis true
/Geometry/PetBox/tile_refl 0.
/Geometry/PetBox/sipm_time_binning 5. picosecond
/Geometry/PetBox/sipm_pde 0.5

### GENERATOR
/Generator/Back2back/region CENTER
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/min_energy 1  eV
#/Generator/SingleParticle/max_energy 1 keV
#/Generator/SingleParticle/region CENTER

### PHYSICS
/process/optical/processActivation Scintillation true
/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/nexus/persistency/start_id 0
/nexus/persistency/outputFile petbox.pet

