### GEOMETRY
/Geometry/PetBox/visibility true
/Geometry/PetBox/tile_type_d HamamatsuVUV
/Geometry/PetBox/tile_type_c HamamatsuVUV
/Geometry/PetBox/single_tile_coinc_plane 0
/Geometry/PetBox/add_teflon_block 1
/Geometry/PetBox/pressure 1.26 bar

/Geometry/PetBox/tile_vis true
/Geometry/PetBox/tile_refl 0.

/Geometry/TileHamamatsuVUV/sipm_cells true

### GENERATOR
/Generator/IonGenerator/region SOURCE
/Generator/IonGenerator/atomic_number 11
/Generator/IonGenerator/mass_number 22
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/min_energy 1  eV
#/Generator/SingleParticle/max_energy 1 keV
#/Generator/SingleParticle/region CENTER

/Actions/PetSensorsEventAction/min_charge 50

### PHYSICS
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/petalosim/persistency/sipm_cells true
/petalosim/persistency/save_tot_charge false

/petalosim/persistency/start_id 0
/petalosim/persistency/output_file petbox.pet

