### GEOMETRY

/Geometry/PETitFBK/tile_refl 0
/Geometry/PETitFBK/sipm_pde 0.3

/Geometry/PETitFBK/sipm_cells true

### GENERATOR
/Generator/IonGenerator/region SOURCE
/Generator/IonGenerator/atomic_number 11
/Generator/IonGenerator/mass_number 22

### PHYSICS
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/petalosim/persistency/sipm_cells true
/petalosim/persistency/save_tot_charge false

/petalosim/persistency/start_id 0
/petalosim/persistency/output_file petit_sat

