### GEOMETRY
/Geometry/PETit/box_vis true
/Geometry/PETit/tile_vis true

/Geometry/PETit/tile_refl 0

### GENERATOR
/Generator/IonGenerator/region CENTER
/Generator/IonGenerator/atomic_number 11
/Generator/IonGenerator/mass_number 22
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/min_energy 1  eV
#/Generator/SingleParticle/max_energy 1 keV
#/Generator/SingleParticle/region CENTER

#/Actions/PetSensorsEventAction/min_charge 50

### PHYSICS
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/petalosim/persistency/start_id 0
/petalosim/persistency/output_file petit

