
### GEOMETRY

/Geometry/FullRingInfinity/depth 3. cm
/Geometry/FullRingInfinity/sipm_pitch 7. mm
/Geometry/FullRingInfinity/inner_radius 165. mm
/Geometry/FullRingInfinity/sipm_rows 20
/Geometry/FullRingInfinity/instrumented_faces 1
/Geometry/FullRingInfinity/specific_vertex 0. 166. 0. mm

/Geometry/SiPMpet/efficiency 0.2
/Geometry/SiPMpet/visibility true
/Geometry/SiPMpet/size 6. mm


### GENERATION
/Generator/ScintGenerator/region AD_HOC
/Generator/ScintGenerator/nphotons 100000


### VERBOSITIES
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132313

### OUTPUT FILE
/nexus/persistency/start_id 10
/nexus/persistency/outputFile full_ring_lut.pet
